cache:
  paths:
    - vendor

stages:
  - test

.compile-and-test: &compile-and-test
  image: "${CI_BUILD_NAME}"
  stage: test
  script:
    - bundle exec rake compile
    - bundle exec rake

jruby:9.1.7.0:
  <<: *compile-and-test
  before_script:
    - gem update --system
    - gem install bundler --no-doc
    - bundle install --jobs=2 --retry=3
    - apt-get update
    - apt-get install gcc -y

ruby:2.3.1:
  <<: *compile-and-test
  before_script:
    - gem update --system
    - gem install bundler --no-doc
    - bundle install --jobs=2 --retry=3
