cache:
  paths:
    - vendor

stages:
  - test

before_script:
  - gem update --system
  - gem install bundler --no-doc
  - bundle install --jobs=2 --retry=3

.test-specific-version: &test-specific-version
  image: "${CI_BUILD_NAME}"
  stage: test
  script:
    - cc -c -O3 -march=native -fPIC -fno-exceptions -Wall -Wextra -Wmissing-prototypes -Wdiv-by-zero -Wbad-function-cast -Wcast-align -Wcast-qual -Wfloat-equal -Wmissing-declarations -Wnested-externs -Wno-unknown-pragmas -Wpointer-arith -Wredundant-decls -Wstrict-prototypes -Wswitch-enum -Wno-type-limits vendor/main.c -o vendor/main.o
    - bundle exec rake compile
    - bundle exec rake

jruby:9.1.7.0:
  <<: *test-specific-version

ruby:2.3.1:
  <<: *test-specific-version
