cache:
  paths:
    - vendor

stages:
  - test

.compile-and-test: &compile-and-test
  image: "${CI_BUILD_NAME}"
  stage: test
  script:
    - bundle exec rake

before_script:
  - gem update --system
  - gem install bundler --no-doc
  - bundle install --jobs=2 --retry=3

jruby:9.1.7.0:
  <<: *compile-and-test
  before_script:
    - apt-get update
    - apt-get install gcc -y
    - gem update --system
    - gem install bundler --no-doc
    - bundle install --jobs=2 --retry=3

jruby:latest:
  <<: *compile-and-test
  before_script:
    - apt-get update
    - apt-get install git gcc -y
    - gem update --system
    - gem install bundler --no-doc
    - bundle install --jobs=2 --retry=3

ruby:latest:
  <<: *compile-and-test

ruby:2.3.1:
  <<: *compile-and-test
